#!/bin/sh
SERVICE_NAME=ws
PATH_TO_JAR=/usr/local/activehome/org.kevoree.platform.standalone-5.2.5.jar
PARAMS="-Dnode.name=ws -Dnode.bootstrap=/usr/local/activehome/main.kevs -Dversion=5.2.5"
PID_PATH_NAME=/tmp/ws-pid
LOG=/var/log/activehome/ws.log
case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f ${PID_PATH_NAME} ]; then
            nohup java -jar ${PARAMS} ${PATH_TO_JAR} /tmp 2>> ${LOG} >> /dev/null &
                        echo $! > ${PID_PATH_NAME}
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f ${PID_PATH_NAME} ]; then
            PID=$(cat ${PID_PATH_NAME});
            echo "$SERVICE_NAME stoping ..."
            kill ${PID};
            echo "$SERVICE_NAME stopped ..."
            rm ${PID_PATH_NAME}
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f ${PID_PATH_NAME} ]; then
            PID=$(cat ${PID_PATH_NAME});
            echo "$SERVICE_NAME stopping ...";
            kill ${PID};
            echo "$SERVICE_NAME stopped ...";
            rm ${PID_PATH_NAME}
            echo "$SERVICE_NAME starting ..."
            nohup java -jar ${PARAMS} ${PATH_TO_JAR} /tmp 2>> ${LOG} >> /dev/null &
                        echo $! > ${PID_PATH_NAME}
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac
